### ISSUE TITLE
ReferenceError: mqtt is not defined

### ISSUE THREAD

**Issue by deisi** [monteslu/mqtt-serial#4]
hey I just copy pasted the https://github.com/monteslu/mqtt-serial#bindphysical example and changed the mqtt server, username and password and serial port path. when I start the script, I get:

```
osmc@rapi3:~/node$ node -i mqtt_beamer.js 
/home/osmc/node/mqtt_beamer.js:6
var client = mqtt.connect('mqtt://deisi:1883', {username: 'user', password: 'pw'});
                  ^

ReferenceError: mqtt is not defined
    at Object.<anonymous> (/home/osmc/node/mqtt_beamer.js:6:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
```

Im suuper new to node and javascript so I guess its easy issue.

**Comment by deisi** [comment]
So as one can see I'm not a javascript man ^^. But there is a little wrong with the example.

It should be:

``` javascript
var SerialPort = require('serialport');
var bindPhysical = require('mqtt-serial').bindPhysical;
var mqtt = require('mqtt');
```
Otherwise the bind Physical part fails right away. 

But even though this doesn't work for me and I absolutely don't understand. I can verify, that the mqtt part is working, because I get the writing to serialPort messages but my device doesn't react to any command. Occasionally I see the device publish things though.
I used a pseudo terminal to see what ends up after the bindPhysical, and that seems to be correct. I thought its an Encoding issue, but chaning the encoding to base64 didnt change a thing.

**Comment by charlietomo** [comment]
@deisi what did you end up using? I am having similar issues to you, and with some amendments can get reading to work. However it looks like this isn't maintained or used and I would rather use something a bit more mainstream.

**Comment by deisi** [comment]
Hey so after the little adjustment above it worked. However I stopped using it at all, because I changed some wirering at home and this became obsolete.

**Comment by monteslu** [comment]
@deisi @charlietomo sorry to let this issue get stale.  The project isn't abandoned, just got a little busy :)

The node-serialport API changed a bit since I wrote the example.

**Comment by charlietomo** [comment]
@deisi thanks for the reply.

@monteslu great news! Appreciate things get busy. Are you likely to be able to update the example for bind physical - or critique my edits below, added after the #?

```
var SerialPort = require('serialport'); # remove .SerialPort
var bindPhysical = require('mqtt-serial').bindPhysical;
var mqtt = require('mqtt'); # change skynet to mqtt
 
// setup the mqtt client with port, host, and optional credentials 
var client = mqtt.connect('mqtt://[ip]', {username: '[user]', password: '[pass]'});
 
// setup a connection to a physical serial port 
var serialPort = new SerialPort('/dev/ttyUSB0',{
    baudRate: 9600, # capitalise R
    buffersize: 1
});
 
//connects the physical device to an mqtt server 
bindPhysical({
  serialPort: serialPort,
  client: client,
  transmitTopic: '[test]/serialtx',
  receiveTopic: '[test]/serialrx    '
});
```
I can receive incoming messages from my serial port via MQTT (great).
I can't send out properly i.e. no response from my device. My device expects a command ending with the ENTER key being pressed. I suspect it is perhaps as I do not know what to send over MQTT in order to stimulate an ENTER being pressed on the serial port output.

Any help much appreciated.
